### ISSUE TITLE
Embedding JSONPath-selected fragment of JSON

### ISSUE THREAD

**Issue by stanislawosinski** [carrotsearch/gatsby-theme-apidocs#9]
We could provide the JSONPath as an attribute to the `pre` tag.

**Comment by dweiss** [comment]
I'll take a look at this - should be a simple extension based on the current code that extracts fragments and it'll give me a breather from java...

**Comment by dweiss** [comment]
Out of curiosity - do the tests pass for you under gatsby-theme-apidocs\plugins\gatsby-transformer-html?

**Comment by dweiss** [comment]
Seems like tests were outdated, I corrected them.

**Comment by stanislawosinski** [comment]
They may not 😃 I don't yet have CI in this project. I can have look later in the evening.

**Comment by dweiss** [comment]
I've implemented this. I'm not sure whether this will be as helpful as I though because jsonpath only allows you to point at values, so you can't easily grab the key-value pair (for example a specific property + its value). There are also some additional quirks in that the returned value has to be reformatted (because it's an object structure so it has to be converted back to a string).

I'm going to leave this in for now. If it's not helpful, it can always be removed.

**Comment by stanislawosinski** [comment]
> I've implemented this. I'm not sure whether this will be as helpful as I though because jsonpath only allows you to point at values, so you can't easily grab the key-value pair (for example a specific property + its value).

Well, this kind of makes sense, since property+value is not valid JSON. I could think of having another HTML attribute where you provide a list of properties to keep at the top level of the JSON, so that you can ultimately show JSON with, for example, one property.

> There are also some additional quirks in that the returned value has to be reformatted (because it's an object structure so it has to be converted back to a string).

Yeah, I didn't think about that one. I suppose we could have prettier as a dependency or just use native `JSON.stringify()`.

> I'm going to leave this in for now. If it's not helpful, it can always be removed.

+1

**Comment by dweiss** [comment]
I've committed it in with JSON.stringify - works fine.
